relationships:
  - name: apmApplicationCallsInfraElastiCacheMemcachedCluster
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^Datastore/instance/Memcached/[^/]*\\.cache\\.amazonaws\\.com/[0-9]+"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: MEMCACHED
          fields:
            - field: endpoint
              fragments:
                - attribute: metricName__4
                  operations:
                    - operation: capture
                      regex: "(^[^\\.]+\\.[^\\.]+\\.)[^\\.]+\\.[^\\.]+\\.cache\\.amazonaws\\.com$"
                - value: "cfg"
                - attribute: metricName__4
                  operations:
                    - operation: capture
                      regex: "^[^\\.]+\\.[^\\.]+\\.[^\\.]+\\.([^\\.]+\\.cache\\.amazonaws\\.com)$"
            - field: port
                attribute: metricName__5
  